version: '3'
services:
  telegram_assistant:
    image: acecandy/ta-custom:latest
    volumes:
      - ./config:/app/config
      - ./downloads/telegram:/app/downloads/telegram
      - ./downloads/youtube:/app/downloads/youtube
      - ./downloads/temp:/app/temp
    ports:
      - "12321:12321"

    restart: unless-stopped
    container_name: telegram_assistant
    environment:
      - TZ=Asia/Shanghai 